### ISSUE TITLE
Issue with key 'annotation'

### ISSUE THREAD

**Issue by Rachine** [juanmc2005/SpeakerEmbeddingLossComparison#4] opened 2020-10-26 15:42 UTC
Hello,

Thank you for the code and the package, it is very helpful. 

As you mentioned in your Readme pyannote is moving very fast. Pyannote core might have changed. 

Especially, the latest pyannote database needs to be installed from dev branch with its latest changes: 

https://github.com/pyannote/pyannote-database

**Comment by juanmc2005** [comment] 2020-10-26 16:03
Hello @Rachine ,

Thank you for your comment.
Are you running into any specific problem with pyannote.database?
If so, it would be great if you could post a stacktrace and a minimal reproducing example so I can try to fix it or look for a compatible version.

Thanks !

**Comment by Rachine** [comment] 2020-10-29 12:06
Hello, 

the error was popping up in the `get_embedding` function in the reproduce notebook. The version was `pyannote.database` 4.0.1 when it was not working, and I had to install from the master branch to make it work. 
```
# A function to crop the embeddings from a file
def get_embedding(file, pretrained, mean=False):
    emb = []
    for f in file.files():
        if 'try_with' in f:
            segments = f['try_with'] #### HERE
        else:
            segments = f['annotation'].get_timeline() 
        for segment in segments: #### HERE
            for mode in ['center', 'loose']: 
                e = pretrained.crop(f, segment, mode=mode)
                if len(e) > 0:
                    break
            emb.append(e)
    emb = np.vstack(emb)
    if mean:
        emb = np.mean(emb, axis=0, keepdims=True)
    return emb
```

**Comment by juanmc2005** [comment] 2020-11-02 11:01
Hi @Rachine, thank you for the information and sorry for the delay.

So if I understand correctly, the master branch of `pyannote.database` is currently only 5 commits behind develop, and version 4.0.1 dates from June 2020. Since your problem comes from the 'annotation' key, I'm guessing it must have something to do with [this commit](https://github.com/pyannote/pyannote-database/commit/61e008ab7d2b76fa694e5adfdd5ff47797d82b84), that affects `SpeakerDiarizationProtocol`.

Are you sure you were working with version 4.0.1 and not with the latest changes in the develop branch ?
Also, can you post the stacktrace of the error you're getting ? A bug might have been introduced in `pyannote.database` because (if my memory doesn't fail me) `SpeakerVerificationProtocol` inherits from `SpeakerDiarizationProtocol`.

**Comment by Rachine** [comment] 2020-11-02 14:53
oops I meant the develop branch of pyannote.database was necessary, I did not notice the main/default branch of pyannote.database is develop.

**Comment by Rachine** [comment] 2020-11-02 14:55
> Hello,
> 

This comment becomes:
> the error was popping up in the `get_embedding` function in the reproduce notebook. The version was `pyannote.database` 4.0.1 when it was not working, and I had to install from the **develop** branch to make it work.


> 
> ```
> # A function to crop the embeddings from a file
> def get_embedding(file, pretrained, mean=False):
>     emb = []
>     for f in file.files():
>         if 'try_with' in f:
>             segments = f['try_with'] #### HERE
>         else:
>             segments = f['annotation'].get_timeline() 
>         for segment in segments: #### HERE
>             for mode in ['center', 'loose']: 
>                 e = pretrained.crop(f, segment, mode=mode)
>                 if len(e) > 0:
>                     break
>             emb.append(e)
>     emb = np.vstack(emb)
>     if mean:
>         emb = np.mean(emb, axis=0, keepdims=True)
>     return emb
> ```

**Comment by juanmc2005** [comment] 2020-11-02 15:33
Oh ok, so it looks as if some bug were introduced and later fixed after the 4.0.1 release.

Judging from the approximate date of the last time I ran the notebook to make sure it worked, it should be compatible with version 3.0.1. However, if you've successfully run it with the latest changes from `develop`, then it should also be compatible with the next release.

I will check the version on my end and specify it in the docs accordingly.
In the following days/weeks I'll try to put together a `requirements.txt` (issue #5) with all the dependencies so these problems don't appear anymore.

Thanks for reporting this!

**Comment by hbredin** [comment] 2020-11-02 15:54
@Rachine would that solve the problem if I make a new release with latest `develop` commits?

**Comment by Rachine** [comment] 2020-11-02 16:36
> @Rachine would that solve the problem if I make a new release with latest `develop` commits?

yes!

**Comment by hbredin** [comment] 2020-11-02 19:58
[Done](https://pypi.org/project/pyannote.database/#history).

**Comment by juanmc2005** [comment] 2020-11-02 20:55
Thanks @hbredin ! I'll close this issue and reference the 4.0.2 release in the `requirements.txt` file

**Closed as completed** 2020-11-02 20:55 UTC
Labels: bug
